# Generated by Django 4.2.6 on 2023-10-29 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='users_friends', to=settings.AUTH_USER_MODEL)),
                ('received_friend_requests', models.ManyToManyField(related_name='users_received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('send_friend_requests', models.ManyToManyField(related_name='users_send_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
